language: java
jdk:
  - oraclejdk8
sudo: false
services:
  - mysql
before_script:
  - "mysql -uroot -e \"CREATE SCHEMA IF NOT EXISTS usmtestdb DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
  - "mysql -uroot -e \"GRANT ALL PRIVILEGES ON usmtestdb.* TO 'usm_user'@'localhost' IDENTIFIED BY 'usm_pass';\""
  - "mysql -uroot -e \"FLUSH PRIVILEGES;\""
  # Some extras for Travis-CI only
  - "mysql -uroot -e \"DELETE FROM mysql.user WHERE User = 'travis';\""
  - "mysql -uroot -e \"FLUSH PRIVILEGES;\""
script:
  - "mvn test && mvn cobertura:cobertura > /dev/null" # So that unit test failures are captured
                                                      # This will rerun the test, need a better solution
  # - "mvn cobertura:check" # To be enabled after coverage per class is above 75%
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 4f523273-00ba-49d5-bc3b-27b84da15c79
cache:
  directories:
  - .autoconf
  - $HOME/.m2
notifications:
  email:
    recipients:
      - a0135914@u.nus.edu
      - a0135952@u.nus.edu
      - liyufeng@u.nus.edu
      - jingdong@u.nus.edu
      - jayavignesh@u.nus.edu
      - a0135916@u.nus.edu
      - nikhilmetrani@u.nus.edu
    on_success: change # default: change
    on_failure: always # default: always