language: java
jdk:
  - oraclejdk8
services:
  - mysql
# before_install:
#   - mysql -e "create schema IF NOT EXISTS usmtestdb;GRANT ALL PRIVILEGES ON usmtestdb.* TO travis@127.0.0.1 IDENTIFIED BY '';FLUSH PRIVILEGES;" -uroot
before_script:
  - "mysql -uroot -e \"CREATE SCHEMA IF NOT EXISTS usmtestdb DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
  - "mysql -uroot -e \"GRANT ALL PRIVILEGES ON usmtestdb.* TO 'usm_user'@'localhost' IDENTIFIED BY 'usm_pass';\""
  - "mysql -uroot -e \"FLUSH PRIVILEGES;\""
  # Some extras for Travis-CI only
  - "mysql -uroot -e \"DELETE FROM mysql.user WHERE User = 'travis';\""
  - "mysql -uroot -e \"FLUSH PRIVILEGES;\""

