security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
      callback-uri: https://www.getpostman.com/oauth2/callback

facebook:
  client:
    clientId: 1564256310547655
    clientSecret: 3f3b27fca4160a1e692e3a1687af6ec9
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    clientAuthenticationScheme: form
    scope:
        - email
        - public_profile
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: 73f614184d71565f7233
    clientSecret: c19989e5d94f2880722d40009f25f1a26b00bc97
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope:
        - user:email
  resource:
    userInfoUri: https://api.github.com/user
google:
  client:
    clientId: 744812384697-qnivnv6309du3lvkb9tq0de0t2dmu5oh.apps.googleusercontent.com
    clientSecret: kyzsOxPKbr4SpOJQMLgIU9Dj
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope:
        - openid
        - profile
        - email
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    preferTokenInfo: false

logging:
  level:
#    ROOT: ERROR
    org.springframework.security: DEBUG

database:
  jpa:
    dialect: org.hibernate.dialect.MySQL5Dialect
    showsql: true
    generateddl: true
  datasource:
    driver: jdbc
    url: jdbc:mysql://localhost:3306/usmdevdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: usm_user
    password: usm_pass

spring:
  resources:
    chain:
      enabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

# config context path to "/" by setting an empty string
server:
  contextPath:

jwt:
  header: Authorization
  secret: auSecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
