USE usmdevdb;
DROP FUNCTION IF EXISTS fn_regexp_like;
CREATE FUNCTION fn_regexp_like (value1 nvarchar(4000),value2 nvarchar(4000)) RETURNS CHAR(1) DETERMINISTIC RETURN value1 REGEXP value2;

INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_CONSUMER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_DEVELOPER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (3, 'ROLE_ADMIN');
INSERT INTO AUTHORITY (ID, NAME) VALUES (4, 'ROLE_MANAGER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (5, 'ROLE_MAINTAINER');

INSERT INTO Category (id, name) VALUES (1, 'Uncategorized');
INSERT INTO Category (id, name) VALUES (2, 'Productivity');
