INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_CONSUMER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_DEVELOPER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (3, 'ROLE_ADMIN');
INSERT INTO AUTHORITY (ID, NAME) VALUES (4, 'ROLE_MANAGER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (5, 'ROLE_MAINTAINER');
